<Project>
  <PropertyGroup>
    <KoreForgeDocsPackageName>KoreForge.Processing.Pipelines</KoreForgeDocsPackageName>
  </PropertyGroup>

  <Target Name="KoreForgeProcessingPipelines_CopyDocs"
          BeforeTargets="PrepareForBuild"
          Condition="'$(SolutionDir)' != '' and Exists('$(SolutionDir)') and '$(DesignTimeBuild)' != 'true'">
    <ItemGroup>
      <_KoreForgeDocFiles Include="$(MSBuildThisFileDirectory)..\contentFiles\any\any\docs\**\*.*" />
    </ItemGroup>

    <PropertyGroup>
      <_KoreForgeDocsTarget>$(SolutionDir)docs\$(KoreForgeDocsPackageName)</_KoreForgeDocsTarget>
    </PropertyGroup>

    <MakeDir Directories="$(_KoreForgeDocsTarget)" Condition="'@(_KoreForgeDocFiles)' != ''" />
    <Copy SourceFiles="@(_KoreForgeDocFiles)"
          DestinationFiles="@(_KoreForgeDocFiles->'$(_KoreForgeDocsTarget)\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true"
          Condition="'@(_KoreForgeDocFiles)' != ''" />
  </Target>
</Project>
